spring:
  application:
    name: pedidos-ms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alurafood-pedidos?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka/
#  instance:
#    instance-id: ${spring.application.name}:${random.value}

#server:
#  port: 0